# from https://github.com/puppetlabs/puppetlabs-dsc/blob/master/appveyor.yml
version: 1.1.x.{build}
skip_commits:
  message: /^\(?doc\)?.*/
clone_depth: 10
init:
- SET
- 'mkdir C:\ProgramData\PuppetLabs\code && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\facter && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\hiera && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\puppet\var && exit 0'
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
matrix:
  fast_finish: true

install:
- SET PATH=C:\Program Files\Puppet Labs\Puppet\bin;C:\Ruby%RUBY_VER%\bin;%PATH%
- ps: |
    $msiPath = "$($env:USERPROFILE)\puppet-agent-5.4.0-x64.msi"
    (New-Object Net.WebClient).DownloadFile('https://downloads.puppetlabs.com/windows/puppet5/puppet-agent-5.4.0-x64.msi', $msiPath)
    cmd /c start /wait msiexec /i $msiPath /q /L* c:\install-puppet.log
- ps: |
    puppet config print config
    puppet config print modulepath
    puppet module install puppetlabs-stdlib
    puppet module install puppetlabs-powershell
    puppet module install maestrodev/wget
- copy /y hiera.yaml C:\ProgramData\PuppetLabs\puppet\etc\hiera.yaml

build: off

test_script:
- ps: |
    puppet apply manifests/site.pp --disable_warnings deprecations --verbose

on_finish:
- ps: Get-ChildItem -Path "C:\Windows\temp"

on_failure:
- cmd: puppet module list --tree
- ps: $PSVersionTable.PSVersion

notifications:
- provider: Email
  to:
  - nobody@nowhere.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
